Create projects with multiple forms
HiWARPs/cactus-backend pull request #14
Opened 2023-03-12 14:41 UTC by rexposadas

# What does this PR do? 

Add the ability to create projects with forms.
Add ability to fetch a form by id. 

# How to test this PR:

Step 1: Create a Project.

You can create a project like so: 
```
curl --location 'http://localhost:3000/project' \
--header 'Content-Type: application/json' \
--data '{
    "name": "p10",
    "forms": [
        {
            "name": "p10 form 1"
        },
        {
            "name": "p10 form 2"
        }

    ]
}'
```

Step 3: Do a GET so that you can see the id of the project.

```bash
curl --location 'http://localhost:3000/project'
```

Step 2: Fetch a form by ID

Pick a project and form id and use that to fetch the form
Replace :pid with the project id. Replace :id with the form id

For example:
```bash
curl --location 'http://localhost:3000/project/:pid/form/:id'
```

You should get the form back. 

# Anything else the reviewer should know about?

2023-03-13 05:55 UTC, wbraynen commented on controllers/form.js
> +    const project = await Project.findById(req.params.pid)
A nitpick, but made me do a double take here, so for the sake of clarity maybe this would be better:
```
const formId = req.params.id
const projectId = req.params.pid

const project = await Project.findById(projectId)
```

2023-03-13 05:56 UTC, wbraynen commented on controllers/form.js
> +    const form = await project.forms.id(req.params.id)
Why not use the `formId` from above?

Seems this should be:
```
const form = await project.forms.id(formId)
```

2023-03-13 05:57 UTC, wbraynen requested changes
Just a few nitpicks.

2023-03-13 13:52 UTC, rexposadas commented
@wbraynen changes made per your request.

2023-03-17 17:13 UTC, DennisT98 approved these changes

2023-03-17 22:48 UTC, wbraynen approved these changes

2023-03-18 21:13 UTC, merged